volumes:
  postgresdb_volume:

services:
  app:
    build: .
    environment:
      - POSTGRES_ADDR=$POSTGRES_ADDR
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - DB_ECHO=$DB_ECHO
    ports: 
      - 8000:8000
    depends_on:
      postgresdb:
        condition: service_healthy
        restart: true

  
  postgresdb:
    image: postgres:18-alpine
    environment:
      - POSTGRES_ADDR=$POSTGRES_ADDR
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - postgresdb_volume:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s
