pytest_plugins = [
    "tests.fixtures.data_creators.acceptance",
    "tests.fixtures.data_creators.good",
    "tests.fixtures.data_creators.posting",
    "tests.fixtures.data_creators.posting_good",
    "tests.fixtures.data_creators.sku",
    "tests.fixtures.data_creators.task",
    "tests.fixtures.dto_models.acceptance",
    "tests.fixtures.dto_models.good",
    "tests.fixtures.dto_models.posting",
    "tests.fixtures.dto_models.posting_good",
    "tests.fixtures.dto_models.sku",
    "tests.fixtures.dto_models.task",
    "tests.fixtures.database",
    "tests.fixtures.repositories",
    "tests.fixtures.client",
]
