"""Initial migration

Revision ID: 2615a2f898b5
Revises: 
Create Date: 2026-04-29 01:16:46.735340

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2615a2f898b5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sku",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuidv7()"),
            nullable=False
        ),
        sa.Column(
            "base_price",
            sa.Numeric(precision=12, scale=2),
            server_default="0.00",
            nullable=False
        ),
        sa.Column(
            "is_hidden",
            sa.Boolean(),
            server_default="f",
            nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False
        ),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "products",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuidv7()"),
            nullable=False
        ),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column(
            "stock",
            sa.Enum("valid", "defect", "not_found", name="stock"),
            server_default="not_found",
            nullable=False
        ),
        sa.Column(
            "reserved_state",
            sa.Boolean(),
            server_default="f",
            nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["sku.id"],
            onupdate="CASCADE",
            ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_index(
        "idx_products_sku_id",
        "products",
        ["sku_id"],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_products_sku_id", table_name="products")
    op.drop_table("products")
    op.drop_table("sku")
    # ### end Alembic commands ###
