"""posting_goods_table

Revision ID: d6deaed4d257
Revises: 964ee737ed17
Create Date: 2026-09-15 19:55:13.823626

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6deaed4d257"
down_revision: str | Sequence[str] | None = "964ee737ed17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posting_goods",
        sa.Column("posting_id", sa.Uuid(), nullable=False),
        sa.Column("good_id", sa.Uuid(), nullable=False),
        sa.Column("good_sku_id", sa.Uuid(), nullable=False),
        sa.Column("good_cost", sa.Numeric(), nullable=False),
        sa.Column("good_stock", sa.String(), nullable=False),
        sa.Column("cancel_reason", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["good_id"], ["goods.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["good_sku_id"], ["sku.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["posting_id"], ["postings.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_posting_goods_good_id"), "posting_goods", ["good_id"], unique=False)
    op.create_index(op.f("ix_posting_goods_good_sku_id"), "posting_goods", ["good_sku_id"], unique=False)
    op.create_index(op.f("ix_posting_goods_posting_id"), "posting_goods", ["posting_id"], unique=False)
    op.create_index(
        "uix_posting_goods_good_id",
        "posting_goods",
        ["good_id"],
        unique=True,
        postgresql_where=sa.text("cancel_reason IS NULL"),
    )

    op.add_column("postings", sa.Column("status", sa.String(), server_default="in_item_pick", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("postings", "status")

    op.drop_index("uix_posting_goods_good_id", table_name="posting_goods")
    op.drop_index(op.f("ix_posting_goods_posting_id"), table_name="posting_goods")
    op.drop_index(op.f("ix_posting_goods_good_sku_id"), table_name="posting_goods")
    op.drop_index(op.f("ix_posting_goods_good_id"), table_name="posting_goods")

    op.drop_table("posting_goods")
    # ### end Alembic commands ###
