"""acceptance and task

Revision ID: 24780ec7f9ff
Revises: bb6c14fa6cd0
Create Date: 2026-08-05 02:55:34.389339

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '24780ec7f9ff'
down_revision: str | Sequence[str] | None = 'bb6c14fa6cd0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'acceptances',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('uuidv7()'),
            nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'postings',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('uuidv7()'),
            nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'tasks',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('uuidv7()'),
            nullable=False
        ),
        sa.Column(
            'status',
            sa.String(),
            server_default='in_work',
            nullable=False
        ),
        sa.Column(
            'task_type',
            sa.String(),
            nullable=False
        ),
        sa.Column(
            'posting_id',
            sa.Uuid(),
            nullable=True
        ),
        sa.Column(
            'acceptance_id',
            sa.Uuid(),
            nullable=True
        ),
        sa.Column(
            'product_id',
            sa.Uuid(),
            nullable=True
        ),
        sa.Column(
            'sku_id',
            sa.Uuid(),
            nullable=False
        ),
        sa.Column(
            'stock',
            sa.String(),
            nullable=False
        ),
        sa.Column(
            'count',
            sa.Integer(),
            nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['acceptance_id'],
            ['acceptances.id'],
            onupdate='CASCADE',
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['posting_id'],
            ['postings.id'],
            onupdate='CASCADE',
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['product_id'],
            ['products.id'],
            onupdate='CASCADE',
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['sku_id'],
            ['sku.id'],
            onupdate='CASCADE',
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_tasks_acceptance_id'),
        'tasks',
        ['acceptance_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_tasks_posting_id'),
        'tasks',
        ['posting_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_tasks_product_id'),
        'tasks',
        ['product_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_tasks_sku_id'),
        'tasks',
        ['sku_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_sku_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_product_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_posting_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_acceptance_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('postings')
    op.drop_table('acceptances')
    # ### end Alembic commands ###
