"""add_discounts_table_add_sku_and_discounts_table

Revision ID: c549fec63dc6
Revises: 6d7b286d2c2f
Create Date: 2026-09-23 19:50:41.842196

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c549fec63dc6"
down_revision: str | Sequence[str] | None = "6d7b286d2c2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discounts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), server_default="0.00", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "sku_and_discounts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("discount_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["discount_id"], ["discounts.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sku_id"], ["sku.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_sku_and_discounts_discount_id"), "sku_and_discounts", ["discount_id"], unique=False)
    op.create_index(op.f("ix_sku_and_discounts_sku_id"), "sku_and_discounts", ["sku_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sku_and_discounts_sku_id"), table_name="sku_and_discounts")
    op.drop_index(op.f("ix_sku_and_discounts_discount_id"), table_name="sku_and_discounts")

    op.drop_table("sku_and_discounts")

    op.drop_table("discounts")
    # ### end Alembic commands ###
