"""add discount percentage to goods table

Revision ID: 6d7b286d2c2f
Revises: d6deaed4d257
Create Date: 2026-09-18 15:46:29.544596

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d7b286d2c2f"
down_revision: str | Sequence[str] | None = "d6deaed4d257"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goods",
        sa.Column("discount_percentage", sa.Numeric(precision=5, scale=2), server_default="0.00", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("goods", "discount_percentage")
    # ### end Alembic commands ###
